FROM registry.access.redhat.com/ubi9/python-39 AS builder
USER root
RUN dnf update -y
RUN dnf  install python3-psycopg2 -y
ADD . /app
RUN  cp /app/.github/local_settings_container.py /app/apimanager/apimanager/local_settings.py
RUN pip install -r /app/requirements.txt
RUN mkdir /logs
RUN touch /logs/gunicorn.access.log
RUN touch /logs/gunicorn.error.log
RUN chgrp -R 0 /logs && chmod -R g+rwX /logs
RUN chown  501 /
RUN chown -R 501 /app
RUN chgrp -R 0 /app && chmod -R g+rwX /app
USER 501
WORKDIR /app
RUN python ./apimanager/manage.py collectstatic --noinput

FROM registry.access.redhat.com/ubi9/nginx-120

COPY --from=builder /app/apimanager/static/* /opt/app-root/src/
RUN chgrp -R 0 /opt/app-root/src/ && chmod -R g+rwX /opt/app-root/src/

# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"


