FROM registry.access.redhat.com/ubi9/python-39 AS builder
USER 0
RUN dnf update -y
RUN dnf  install python3-psycopg2 -y
ADD . ./
RUN  cp .github/local_settings_container.py ./apimanager/apimanager/local_settings.py
RUN mkdir /logs
RUN touch /logs/gunicorn.access.log
RUN touch /logs/gunicorn.error.log
RUN chgrp -R 0 /logs && chmod -R g+rwX /logs
RUN chown -R 1001:0 ./
USER 1001

# Install the dependencies
RUN pip install -U "pip>=19.3.1" && \
    pip install -r requirements.txt && \
    python manage.py collectstatic --noinput && \


FROM nginxinc/nginx-unprivileged
COPY --from=builder ./apimanager/static /usr/share/nginx/html/static/
USER 0
RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx
RUN chgrp -R 0 /usr/share/nginx/ && chmod -R g+rX /usr/share/nginx/
RUN chgrp -R 0 /var/cache/nginx/ && chmod -R g+rwX /var/cache/nginx/
RUN chown -R 1001 /usr/share/nginx/
USER 1001

